trigger:
 - none  

pool:
  name: Devops-agent

steps:


- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar-qube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Devops_zumlo-demo_AZJSHMgFVPEliKEOG96o'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'