trigger:
 - none  

pool:
  name: Devops-agent
steps:


- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar-qube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sqa_e243274fda72a5ae605b29eb44274a33a809f99c'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'