trigger:
 - none  

pool:
  name: Devops-agent

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.402'

- task: NodeTool@0
  inputs:
    versionSpec: '22.0.7'
  displayName: 'Install Node.js'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'            
    jdkArchitectureOption: 'x64'  
    jdkSourceOption: 'PreInstalled' 

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar-qube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Devops_zumlo-demo_AZJSHMgFVPEliKEOG96o'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'